// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/api/[membershipType]/[membershipId]/character/[characterId].ts";
import * as $1 from "./routes/api/close.ts";
import * as $2 from "./routes/api/init.ts";
import * as $3 from "./routes/api/renderdata.ts";
import * as $4 from "./routes/drip/[membershipType]/[membershipId]/character/[characterId].tsx";
import * as $5 from "./routes/drip/[membershipType]/[membershipId]/index.tsx";
import * as $6 from "./routes/index.tsx";
import * as $$0 from "./islands/APILoader.tsx";
import * as $$1 from "./islands/ButtonTest.tsx";
import * as $$2 from "./islands/CharacterSelect.tsx";
import * as $$3 from "./islands/FormTest.tsx";
import * as $$4 from "./islands/ModalContainer.tsx";
import * as $$5 from "./islands/Stage.tsx";

const manifest = {
  routes: {
    "./routes/api/[membershipType]/[membershipId]/character/[characterId].ts":
      $0,
    "./routes/api/close.ts": $1,
    "./routes/api/init.ts": $2,
    "./routes/api/renderdata.ts": $3,
    "./routes/drip/[membershipType]/[membershipId]/character/[characterId].tsx":
      $4,
    "./routes/drip/[membershipType]/[membershipId]/index.tsx": $5,
    "./routes/index.tsx": $6,
  },
  islands: {
    "./islands/APILoader.tsx": $$0,
    "./islands/ButtonTest.tsx": $$1,
    "./islands/CharacterSelect.tsx": $$2,
    "./islands/FormTest.tsx": $$3,
    "./islands/ModalContainer.tsx": $$4,
    "./islands/Stage.tsx": $$5,
  },
  baseUrl: import.meta.url,
};

export default manifest;
